/**
 * ---------------------
 * 🚗🚦 Generated by nuxt-typed-router. Do not modify !
 * ---------------------
 * */

import { defineNuxtPlugin } from '#app';

export default defineNuxtPlugin((nuxtApp) => {
  const routesList = {
    airlines: 'airlines',
    airports: 'airports',
    cities: 'cities',
    flights: 'flights',
    index: 'index',
    login: 'login',
    planes: 'planes',
    register: 'register',
    users: 'users',
  };

  return {
    provide: {
      typedRouter: nuxtApp.$router,
      routesList,
    },
  };
});
